// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ExecuteSection: typeof import('./src/components/ExecuteSection.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LoggingLevels: typeof import('./src/components/LoggingLevels.vue')['default']
    OutputConsole: typeof import('./src/components/OutputConsole.vue')['default']
    ProvidePrakContext: typeof import('./src/components/ProvidePrakContext.vue')['default']
    SourceFolderList: typeof import('./src/components/SourceFolderList.vue')['default']
    TargetFolderList: typeof import('./src/components/TargetFolderList.vue')['default']
  }
}
