// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnalysisExtensionsStats: typeof import('./src/components/AnalysisExtensionsStats.vue')['default']
    AnalysisStat: typeof import('./src/components/AnalysisStat.vue')['default']
    AnalysisView: typeof import('./src/components/AnalysisView.vue')['default']
    BigButton: typeof import('./src/components/BigButton.vue')['default']
    Brand: typeof import('./src/components/Brand.vue')['default']
    BrandCenter: typeof import('./src/components/BrandCenter.vue')['default']
    BrandLeft: typeof import('./src/components/BrandLeft.vue')['default']
    CopySettingsDrawer: typeof import('./src/components/CopySettingsDrawer.vue')['default']
    ExtensionsSelect: typeof import('./src/components/ExtensionsSelect.vue')['default']
    FolderListItem: typeof import('./src/components/FolderListItem.vue')['default']
    Layout: typeof import('./src/components/Layout.vue')['default']
    LoadingBar: typeof import('./src/components/LoadingBar.vue')['default']
    LoggingLevels: typeof import('./src/components/LoggingLevels.vue')['default']
    Menu: typeof import('./src/components/Menu.vue')['default']
    MenuOption: typeof import('./src/components/MenuOption.vue')['default']
    NormalButton: typeof import('./src/components/NormalButton.vue')['default']
    OutputArea: typeof import('./src/components/OutputArea.vue')['default']
    OutputConsole: typeof import('./src/components/OutputConsole.vue')['default']
    OverviewText: typeof import('./src/components/OverviewText.vue')['default']
    ProvidePrakContext: typeof import('./src/components/ProvidePrakContext.vue')['default']
    ResultInfos: typeof import('./src/components/ResultInfos.vue')['default']
    ResultStat: typeof import('./src/components/ResultStat.vue')['default']
    SelectMultiple: typeof import('./src/components/SelectMultiple.vue')['default']
    SettingsDrawer: typeof import('./src/components/SettingsDrawer.vue')['default']
    SourceFoldersSelector: typeof import('./src/components/SourceFoldersSelector.vue')['default']
    StartView: typeof import('./src/components/StartView.vue')['default']
    StepOneBar: typeof import('./src/components/StepOneBar.vue')['default']
    StepOneView: typeof import('./src/components/StepOneView.vue')['default']
    StepTitle: typeof import('./src/components/StepTitle.vue')['default']
    StepTwoView: typeof import('./src/components/StepTwoView.vue')['default']
    TargetFolderList: typeof import('./src/components/TargetFolderList.vue')['default']
    TargetStructureSelect: typeof import('./src/components/TargetStructureSelect.vue')['default']
    VeryBigButton: typeof import('./src/components/VeryBigButton.vue')['default']
  }
}
